{
	"name": "Node.js CI",
	"on": {
		"push": { "branches": ["master"] },
		"pull_request": { "branches": ["master"] },
		"workflow_dispatch": {}
	},
	"jobs": {
		"build": {
			"runs-on": "ubuntu-latest",
			"strategy": {
				"matrix": { "node-version": ["20.x", "22.x", "24.x"] }
			},
			"steps": [
				{ "uses": "actions/checkout@v5.0.0" },
				{
					"name": "Use Node.js ${{ matrix.node-version }}",
					"uses": "actions/setup-node@v6.0.0",
					"with": {
						"node-version": "${{ matrix.node-version }}",
						"cache": "npm"
					}
				},
				{ "run": "npm ci" },
				{ "run": "npm run build --if-present" },
				{ "run": "npm run lint" },
				{ "run": "npm test" }
			]
		}
	}
}
