{
	"name": "Node.js Package",
	"on": {
		"release": { "types": ["published"] },
		"workflow_dispatch": {}
	},
	"jobs": {
		"build": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{ "uses": "actions/checkout@v5.0.0" },
				{
					"uses": "actions/setup-node@v6.0.0",
					"with": {
						"node-version": 24
					}
				},
				{ "run": "npm ci" },
				{ "run": "npm test" }
			]
		},
		"publish-npm": {
			"needs": "build",
			"runs-on": "ubuntu-latest",
			"permissions": { "id-token": "write" },
			"steps": [
				{ "uses": "actions/checkout@v5.0.0" },
				{
					"uses": "actions/setup-node@v6.0.0",
					"with": {
						"node-version": 24,
						"registry-url": "https://registry.npmjs.org/"
					}
				},
				{ "run": "npm ci" },
				{
					"run": "npm publish",
					"env": {
						"NODE_AUTH_TOKEN": "${{secrets.npm_token}}"
					}
				}
			]
		}
	}
}
